port: 9200
modes:
  dev: 'development'
  prod: 'production'
entries:  # entries下配置的path相对src目录
  -
    name: 'audit'
    title:
      development:  '审核平台-开发'
      production: '审核管理平台'
    entry: 'audit/index.js'
    template: 'audit/index.html'
    favicon: 'audit/assets/images/AUDIT.favicon.ico'
    filename:
      development:  'audit/index.html'
      production: '../audit/index.html'
proxy: './proxy.config.js'
mock: './mock.config.js'