port: 9200
modes:
  dev: 'development'
  prod: 'production'
entries:  # entries下配置的path相对src目录
  -
    name: 'admin'
    title:
      development:  '权限管理平台-开发'
      production: '权限管理平台'
    entry: 'admin/index.js'
    template: 'admin/index.html'
    favicon: 'admin/assets/images/admin.favicon.ico'
    filename:
      development:  'admin/index.html'
      production: '../admin/index.html'
proxy: './proxy.config.js'
mock: './mock.config.js'